### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by JohhnyKinuthia** [localsend/localsend#226] opened 2023-03-02 06:21 UTC
### Describe the bug

Localsend is unable to start on Windows 11 due to socket error.

### To reproduce

1. Open LocalSend on Windows 11
2. Localsend displays an error notification that it's unable to bind to port

### Expected behavior

Localsend should start successfully

### Screenshots

![image](https://user-images.githubusercontent.com/51368005/222347006-cf8784f4-34c5-44c5-9762-8de0ea2692d3.png)

### Desktop (please complete the following information)

- OS: Windows 11 Build 22621

**Comment by Tienisto** [comment] 2023-03-05 13:38
Duplicate of #125

**Closed by Tienisto** 2023-03-05 13:38 UTC
Labels: bug, duplicate
