### ISSUE TITLE
Add this app to share menu extension when any folder is clicked in macos

### ISSUE THREAD

**Issue by heyswayam** [localsend/localsend#1290] opened 2024-04-25 14:28 UTC
### Is your feature request related to a problem? Please describe.

No its not related to any bugs but when I click share it doesnt show up. 
<img width="500" alt="image" src="https://github.com/localsend/localsend/assets/96104753/b8b302f9-f868-4dab-953a-6ecf60b65bd9">

### Describe the solution you'd like

I tried to look it up, it says you need to just do some changes in the app bundle to include it

https://stackoverflow.com/questions/76404963/i-want-to-add-my-electron-app-to-macs-share-menu-extension-when-any-folder-is

### Describe alternatives you've considered

I dont seem to find any alternative. But since most of us rely on it heavily it would be great if you guys can add it

**Comment by ItsukaHiro** [comment] 2024-04-28 01:13
Yeah, I also want it appear on share menu on Windows.

**Comment by teekamsuthar** [comment] 2024-08-10 07:45
Any update on this?

**Comment by ShlomoCode** [comment] 2024-09-25 15:46
Duplicate of https://github.com/localsend/localsend/issues/586. will be in the next release (v1.16.0)

**Closed** 2024-09-26 00:41 UTC
