### ISSUE TITLE
Bug report about IOS18

### ISSUE THREAD

**Issue by JoeYang65** [localsend/localsend#2011] opened 2024-11-05 15:06 UTC
### Describe the bug

After upgrading to iOS 18.1, the photo app cannot use LocalSend for sharing. Unable to call localsend through other apps。

### To reproduce

1. Go to 'Photo' app
2. Click on 'share'
3. Scroll down to 'LocalSend'
4. See error， Pop up window appears, but there is no jump

### Expected behavior

Jump to localSend and send the image to the specified device

### Desktop (please complete the following information)

-Computer OS： Windows 11
-Version ：LocalSend [v1.16.1]

### Smartphone (please complete the following information)

-Device：iPhone 12 pro max
-OS： IOS18.1
-Version：LocalSend [v1.16.1]

**Comment by Tienisto** [comment] 2024-11-06 00:04
Duplicate of #2002

**Closed by Tienisto** 2024-11-06 00:04 UTC
