### ISSUE TITLE
v1.16.0: SocketException: Failed to create server socket 

### ISSUE THREAD

**Issue by netcharm** [localsend/localsend#1992] opened 2024-11-03 07:53 UTC
### Describe the bug

Version 1.16,0 armv8
SocketException: Failed to create server socket (OS Error: The shared flag to bind() needs to be `true` if binding multiple times on the same (address, port) combination.), address = 0.0.0.0, port = 53317.

### To reproduce

1. start app and then `Swipe Back` to launch desktop
2. press app icon to active app, will prompt the error
3. See error

### Expected behavior

if `Swipe Up` to Launch Desktop, not `Swipe Back`, no this error.

### Screenshots

![Screenshot_20241103_153954](https://github.com/user-attachments/assets/9a9e3e4e-ae08-47dd-9ed5-03c16506e67f)

### Desktop (please complete the following information)

Android 10

### Smartphone (please complete the following information)

Honor Play5, Android 10

**Comment by netcharm** [comment] 2024-11-03 07:55
![Screenshot_20241103_153954](https://github.com/user-attachments/assets/a2919849-23f4-49fd-92d2-d52f1d19e13e)

**Comment by nizhiyi** [comment] 2024-11-03 12:52
same with me

**Comment by Scratch-net** [comment] 2024-11-03 13:46
same on windows desktop

**Comment by Tienisto** [comment] 2024-11-03 13:52
How do you reproduce this on Desktop? @Scratch-net

**Comment by Scratch-net** [comment] 2024-11-03 13:58
I just installed it using X86-64 installer and launched it and immediately got this error

**Comment by Tienisto** [comment] 2024-11-03 14:03
Make sure that you don't have another LocalSend process open @Scratch-net 

Seems like a regression similar to #1568
I've fix this in 140546591ebc333fa06cd6605eae3f43066aa6b0

**Comment by Scratch-net** [comment] 2024-11-03 14:10
I do have only one LocalSend process running. Will wait for the fix

**Comment by Tienisto** [comment] 2024-11-03 14:28
@Scratch-net , My fix likely won't fix your issue. It only fixes the exit behaviour of the app for the "back" gesture on Android.

I just tried the exe installer again, and it worked on my Windows PC.

**Comment by Scratch-net** [comment] 2024-11-03 14:34
I have several network interfaces on my PC (wifi, docker, etc) might it be the reason? 
I've checked with TCPMon and this port isn't opened by anyone else
Changing port does remove the error, however I still cannot receive files on PC, only send, though android sees it and firewall is configured correctly

**Comment by Tienisto** [comment] 2024-11-03 14:49
@Scratch-net does the previous version work? Can you reboot the computer? It seems that your error message is different than this issue.

**Comment by Scratch-net** [comment] 2024-11-03 14:55
Error message is exactly the same as the one above. 1.15.4 gives the same message

**Comment by DmitryN71** [comment] 2024-11-03 16:52
Same SocketException on Galaxy S24+, Android 14.

**Comment by Scratch-net** [comment] 2024-11-03 17:03
Couple reboots helped

**Comment by adeii** [comment] 2024-11-03 19:51
With flutter DLL and data folder from LocalSend 1.15.1, new LocalSend 1.16 works on Win 7.
Works fine with EMUI 8.0.

**Comment by Tienisto** [comment] 2024-11-05 00:21
Fixed in `v1.16.1`

**Closed by Tienisto** 2024-11-05 00:21 UTC
Labels: bug, android

**Comment by user1823** [comment] 2024-12-05 11:21
I sometimes get this error on Android in v.1.16.1 too. Not sure about the reproduction steps.
