### ISSUE TITLE
Feature request:send files or information to them through web pages

### ISSUE THREAD

**Issue by cutejsf** [localsend/localsend#1856] opened 2024-10-03 04:52 UTC
### Is your feature request related to a problem? Please describe.

只要安装了应用程序或应用程序，一方就可以充当服务器吗？而即使没有安装软件，另一方也可以向他们发送文件或信息。例如，计算机上安装了本地发送应用程序。手机可以通过网页向他发送文件或消息

Can one party act as a server as long as the app or application is installed, while the other party can send files or information to them through web pages even if the software is not installed
For example, the localsend application is installed on the computer
Mobile phones can send files or messages to him through web pages

### Describe the solution you'd like

thanks

**Comment by Tienisto** [comment] 2024-10-03 11:53
Duplicate of #424

**Closed by Tienisto** 2024-10-03 11:53 UTC
