### ISSUE TITLE
Extensive Loading in case of large files

### ISSUE THREAD

**Issue by kryptobolt200528** [localsend/localsend#532] opened 2023-06-14 10:17 UTC
### Describe the bug

First of all thank you for this beautiful and excellent app.
When a large file is selected for transfer,there is extensive loading(in my case the file was >5gb).
However similar apps to local send have little or no loading when sending the same file, I don't know if it has to do with the specific way local send caches or transfers files but the loading time is way too much(around 6 minutes)

### To reproduce

https://github.com/localsend/localsend/assets/72438196/23097e17-2443-4898-bc86-24fb1f696ea1

### Expected behavior

The local time of the file should not exceed 1-2 mins as it becomes annoying,also similar apps have little to no loading time

### Desktop (please complete the following information)

Android 11
1.10.0

### Smartphone (please complete the following information)

Realme 6 pro(RMX 2061)
Android 11
1.10.0

**Comment by Tienisto** [comment] 2023-06-14 15:24
This is a Flutter issue as it needs to copy the file to a temporary path to be able to work with.

Specifically, this happens on Android and iOS as far as I know.

**Comment by abe1242** [comment] 2023-08-26 07:36
I just noticed that this problem is not present when you are sending a folder. I just selected a folder with about 5 files, which makes a total of 17GB and it just loads instantly.
So I'm thinking there might be a workaround for individual files too

**Comment by kryptobolt200528** [comment] 2023-08-26 15:23
> I just noticed that this problem is not present when you are sending a folder. I just selected a folder with about 5 files, which makes a total of 17GB and it just loads instantly. So I'm thinking there might be a workaround for individual files too

Thanks for the tip

**Comment by luiguangguan** [comment] 2024-01-04 06:41
So is this problem caused by Flutter, and therefore cannot be resolved? Additionally, I believe this issue not only leads to extended waiting times for writing large files to the cache but also significantly consumes the storage space on the mobile device. Let me illustrate with an extreme example.

Suppose I need to send a 20GB file, but the remaining storage space on my phone is already less than 20GB. In such a scenario, it seems that the file may not be sent, which is quite problematic.

Therefore, I am keen on finding a solution to address this issue. I am concerned about the substantial impact it has on the user experience, particularly in situations where users might want to send large files.

I hope this matter receives the attention of the project developers, as resolving it would greatly enhance the overall functionality and usability of the application. Your consideration and assistance in resolving this concern would be highly appreciated.

所以这个问题是因为Flutter问题导致的，因此无法解决吗？
另外我认为这个问题除了导致发送大文件需要长时间等待写入缓存，还大量占用手机的存储空间。我举一个极端的例子。
我需要发送一个20GB的文件，但是我手机里的剩余存储空间已经小于20GB时，文件可能无法发送了，这显得很糟糕。
所以我很希望能够解决这个问题。
希望能够得到项目开发者的重视。

**Comment by luiguangguan** [comment] 2024-01-04 07:00
As a user with OCD tendencies, having to write to the disk every time I send a file can impact the write lifespan of the storage. At least as a user, it creates a psychological discomfort.

**Comment by Tienisto** [comment] 2024-01-05 14:10
@luiguangguan I am aware about this problem. The workaround would be to move the large file into a separate folder and send the folder instead.

There is an issue that tracks the current problem: https://github.com/miguelpruivo/flutter_file_picker/issues/561

Theoretically, it should be possible to fix this by somehow integrating the fork https://github.com/abhi16180/flutter_file_picker that doesn't copy the file if `MANAGE_EXTERNAL_STORAGE` permission is given.

However, this fork is already outdated compared to the upstream file_picker package. I wish that this fork gets somehow merged.

**Comment by kryptobolt200528** [comment] 2024-01-18 06:00
Hey,thanks for explaining the cause of the issue,however what @luiguangguan says makes complete sense,other similar apps don't seem to have this problem,as a newbie coder i think this might be due to them using java or some other workaround🤔,but i think that the said workaround needs to be implemented as considering the virtual situation provided by @luiguangguan is quite realistic.

**Comment by Tienisto** [comment] 2024-07-14 15:09
Closed with #1501

**Closed by Tienisto** 2024-07-14 15:09 UTC
Labels: enhancement
