### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ZRyanX** [localsend/localsend#538] opened 2023-06-17 03:04 UTC
### Is your feature request related to a problem? Please describe.

In the win11 system, it is very troublesome to click on the software interface every time you share a file.  So it will be very convenient if you can share the file when you select it in 'explorer.exe'.

### Describe the solution you'd like

I hope that in the win11 system, the software supports the sharing mode in the pop-up sharing box when you select a file in the 'Explorer.exe' and right-click the share button.
At present, the same type of software named intel unison already supports this function.

### Additional context

![Screenshot_20230617_103921_com huawei smarthome_edit_958993769684](https://github.com/localsend/localsend/assets/73228132/50d757bb-0380-4223-a070-5588b3df240f)
![Screenshot_20230617_103933_com huawei smarthome_edit_939468683858](https://github.com/localsend/localsend/assets/73228132/d3cec897-c766-407b-8297-f5b8d59ce80b)

**Comment by Tienisto** [comment] 2023-12-10 01:01
Duplicate of #115

**Closed by Tienisto** 2023-12-10 01:01 UTC
