### ISSUE TITLE
Feature request Text sent from the clipboard can be displayed in the history.

### ISSUE THREAD

**Issue by SkywalkerJi** [localsend/localsend#1455] opened 2024-07-03 02:01 UTC
### Is your feature request related to a problem? Please describe.

Currently, the chat history only includes files and does not contain the text content sent or clipboard text. I hope a copy of the text can be retained in the chat history. This way, I can use quick save to retain the text content instead of needing to copy it each time I send it.

### Describe the solution you'd like

I hope to view the received text content and clipboard text in the chat history page.When quick save is enabled, it can continuously receive text and clipboard content.

### Describe alternatives you've considered

Alternatively, an option could be added to write the received text information as a plain text file into the download directory.

**Comment by Tienisto** [comment] 2024-07-08 19:48
Duplicate of #1342

**Closed by Tienisto** 2024-07-08 19:48 UTC
Labels: enhancement
