### ISSUE TITLE
[Feature request] Automatically pass the contents of the clipboard between devices

### ISSUE THREAD

**Issue by xiaomi2077** [localsend/localsend#187] opened 2023-02-21 11:24 UTC
### Is your feature request related to a problem? Please describe.

First,thank you for contributing such an excellent project.

I've used a similar app called `kde connect` [kde connect](https://kdeconnect.kde.org/),which is also a cross-platform app.It has a feature called `Send clipboard`. When I copy a piece of text on my Android phone, it automatically sends it to another device it's paired with, like Ubuntu. This operation is intuitive and requires no additional action. 

I know that the current version of the `Local Send` can provide the ability to pass text between different devices. But I need to manually enter the text, click Confirm, and then select the device I want to send to complete the cross-device flow of the text. The operation is more cumbersome.

### Describe the solution you'd like

When I copy text on one device, it is automatically forwarded to the clipboard of the other paired device

**Comment by Tienisto** [comment] 2023-02-21 11:36
Duplicate of #163

**Closed by Tienisto** 2023-02-21 11:36 UTC

**Comment by Tienisto** [comment] 2023-02-21 11:41
Currently, this is quite complicated because on Android this app doesn't run in background.

It is possible to automatically copy to clipboard on the receiving Windows/Mac/Linux device though.
