### ISSUE TITLE
Bug report: win x64 1.15.3(53) can't run on port:53317

### ISSUE THREAD

**Issue by ZmdnaHF0ZmFqYXZ0O** [localsend/localsend#1665] opened 2024-08-19 17:54 UTC
### Describe the bug

Dear developer,
It couldn't run on port:53317, so I changed port to other ports:5679 and 2227, it works, is it a bug?

### To reproduce

Run the version win x64 zip 1.15.3(53), and it shows a error.

### Expected behavior

is it a bug?

### Screenshots

![image](https://github.com/user-attachments/assets/2489ce58-f1b3-40f5-9739-02683cf1b773)

**Comment by brogers5** [comment] 2024-08-20 03:46
Possible duplicate of https://github.com/localsend/localsend/issues/125.

**Closed** 2024-08-20 09:39 UTC
