### ISSUE TITLE
Target Folder on SD Card

### ISSUE THREAD

**Issue by RealVegOs** [localsend/localsend#896] opened 2023-11-14 19:40 UTC
### Describe the bug

LocalSend works well for me, if I leave the default target folder untouched. If I create a folder on my SD card, transfer from PC fails. I get an error like not allowed. But I allowed files and media in apps settings. When I created the folder on my SD card, I also had to allow access. I do not want to store much on the internal storage as I have a huge SD card. The other direction, from tablet to PC works without any problems. 

### To reproduce

 I hope this report is no dublicate.  

### Expected behavior

 Thanks much.

### Desktop (please complete the following information)

Latest Debian stable

### Smartphone (please complete the following information)

Lenovo Tab8 4th Gen
with Android 13

**Comment by Tienisto** [comment] 2023-11-30 01:15
Duplicate of #710

**Closed by Tienisto** 2023-11-30 01:15 UTC
