### ISSUE TITLE
Bug report  Ver 1.15.0 can‘t send the huge file(    20 Gb single file ), it is crashed.

### ISSUE THREAD

**Issue by xiaojiaqi** [localsend/localsend#1557] opened 2024-07-24 13:50 UTC
### Describe the bug

 Ver 1.15.0 can‘t send the huge file(   20Gb  single file ), the send client is crashed.

### To reproduce

the client is crashed.

### Expected behavior

The file was successfully transferred.

### Smartphone (please complete the following information)

-Device： Pc
-Os： windows 10
-version: v1.15.0(48)

**Comment by Tienisto** [comment] 2024-07-24 13:51
Duplicate of #240. Already fixed in #1547. Please wait for the next release

**Closed by Tienisto** 2024-07-24 13:51 UTC
