### ISSUE TITLE
Can right-click menus be added to the Windows platform? 

### ISSUE THREAD

**Issue by heyeruoqi** [localsend/localsend#1032] opened 2023-12-14 11:12 UTC
### Is your feature request related to a problem? Please describe.

Can right-click menus be added to the Windows platform? Of course, other computer platforms such as Mac also hope to add this feature. If you can right-click on the file > use Localsend to send, it is more convenient and immersive than dragging.

### Describe the solution you'd like

no

### Describe alternatives you've considered

no

**Comment by Tienisto** [comment] 2023-12-14 13:09
Duplicate of #115

**Closed by Tienisto** 2023-12-14 13:08 UTC
