### ISSUE TITLE
add ipv6 support please

### ISSUE THREAD

**Issue by kirito201711** [localsend/localsend#1932] opened 2024-10-23 09:39 UTC
### Is your feature request related to a problem? Please describe.

It shouldn’t be difficult to add ipv6 support, can you support it?

### Describe the solution you'd like

Listen on ipv6 address

### Additional context

In some areas, the optical fiber is allocated to intranet ipv4 and public network ipv6. If you monitor the intranet ipv4, you cannot send files to friends, but if you monitor ipv6, you can send files to distant friends.

**Comment by Tienisto** [comment] 2024-10-23 12:35
Duplicate of #549

**Closed by Tienisto** 2024-10-23 12:35 UTC

**Comment by l4kr** [comment] 2024-11-25 17:15
ipv6 not detected, opinion rejected

**Comment by kirito201711** [comment] 2024-12-13 04:11
> ipv6 not detected, opinion rejected

https://whatismyipaddress.com/
Here you can see your ipv6 address

**Comment by kirito201711** [comment] 2024-12-13 04:13
> > ipv6 not detected, opinion rejected
> 
> https://whatismyipaddress.com/ Here you can see your ipv6 address

You only need to listen to “::1” to achieve it, it is very simple
