### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by NoAIGhost** [localsend/localsend#330] opened 2023-03-26 05:31 UTC
### Describe the bug

DioError [DioErrorType.other]: SocketException: 远程计算机拒绝网络连接。
 (OS Error: 远程计算机拒绝网络连接。
, errno = 1225), address = 192.168.0.191, port = 1105
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483)
#2      DioMixin.post (package:dio/src/dio_mixin.dart:97)
#3      SendNotifier.startSession (package:localsend_app/provider/network/send_provider.dart:116)
<asynchronous suspension>

### To reproduce

DioError [DioErrorType.other]: SocketException: 远程计算机拒绝网络连接。
 (OS Error: 远程计算机拒绝网络连接。
, errno = 1225), address = 192.168.0.191, port = 1105
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483)
#2      DioMixin.post (package:dio/src/dio_mixin.dart:97)
#3      SendNotifier.startSession (package:localsend_app/provider/network/send_provider.dart:116)
<asynchronous suspension>

### Expected behavior

DioError [DioErrorType.other]: SocketException: 远程计算机拒绝网络连接。
 (OS Error: 远程计算机拒绝网络连接。
, errno = 1225), address = 192.168.0.191, port = 1105
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:488)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:483)
#2      DioMixin.post (package:dio/src/dio_mixin.dart:97)
#3      SendNotifier.startSession (package:localsend_app/provider/network/send_provider.dart:116)
<asynchronous suspension>

**Comment by Tienisto** [comment] 2023-03-26 16:39
Duplicate of #168

**Closed by Tienisto** 2023-03-26 16:39 UTC

**Comment by NoAIGhost** [comment] 2023-04-01 04:43
> Duplicate of #168

知道原因了，ios端设置不加密就可以了
