### ISSUE TITLE
Add list of received file.

### ISSUE THREAD

**Issue by zx1035074931** [localsend/localsend#142] opened 2023-02-09 14:06 UTC
### Add list of received file.

There is no "List of received file" in the App. So, when I want to open the received file, I have to leave the App and go to the system’s file manager and find it. This is really not convenient especially in IOS/Android phone. 

Can you add a tab like "files" to show the list.

**Comment by Tienisto** [comment] 2023-02-09 14:32
Hi, this is a duplicate of #87 

Furthermore, this has been implemented in `v1.7.0` but it is not released yet: https://github.com/localsend/localsend/blob/main/assets/CHANGELOG.md

**Closed by Tienisto** 2023-02-09 14:32 UTC
