### ISSUE TITLE
Feature request: ipv6 support

### ISSUE THREAD

**Issue by chencl0214** [localsend/localsend#601] opened 2023-08-02 09:37 UTC
### Is your feature request related to a problem? Please describe.

I tried to use two ipv6 addresses that can be pinged to transfer files to each other, but it failed. It seems that the IP input does not support ipv6.

### Describe the solution you'd like

What I want to see is that entering an ipv6 address can connect normally and transfer files to each other.

**Comment by Tienisto** [comment] 2023-08-02 23:36
Duplicate of #549

**Closed by Tienisto** 2023-08-02 23:36 UTC
