### ISSUE TITLE
Program is running but can't see or not visible in Windows 10 desktop

### ISSUE THREAD

**Issue by atpersian** [localsend/localsend#637] opened 2023-08-27 19:36 UTC
### Describe the bug

Localsend is running but can't see or not visible in Windows 10 desktop while it work  before last windows update correctly .

### To reproduce

Program is running but can't see or not visible in Windows 10 desktop . its icon see in desktop  but i cant see it panel

### Expected behavior

Program is running but can't see or not visible in Windows 10 desktop . its icon see in desktop  but i cant see it panel

### Screenshots

![2023-08-27 23_03_47-New Issue · localsend_localsend — Mozilla Firefox](https://github.com/localsend/localsend/assets/10154730/766c1cb1-384a-4476-9cce-f57fd95ba936)

### Desktop (please complete the following information)

Windows 10 Enterprise
22H2

**Comment by Tienisto** [comment] 2023-08-27 19:41
Does it show up when you send files to the PC?

**Comment by atpersian** [comment] 2023-08-27 19:44
thank  for  your quick replay dude.  i try uninstall it and remove  it  all bellow file . install it again and it work normally .
![2023-08-27 23_12_36-localsend - Everything](https://github.com/localsend/localsend/assets/10154730/6780cf3e-8412-4562-8c80-68acb7411438)

**Comment by Tienisto** [comment] 2023-08-27 20:53
I will close this for now because it seems not to be reproducible

**Closed by Tienisto** 2023-08-27 20:53 UTC
