### ISSUE TITLE
Provide a Linux on ARM64 build

### ISSUE THREAD

**Issue by proletarius101** [localsend/localsend#101] opened 2023-02-01 13:17 UTC
Linux on ARM64 is growing in popularity. It would be nice to have a Linux on ARM64 build.

I can include it in https://github.com/flathub/flathub/pull/3869.

**Comment by Tienisto** [comment] 2023-02-01 14:09
I have no ARM computer and Github actions do not provide ARM runners AFAIK.

https://github.com/flutter/flutter/issues/74929

**Comment by kero990** [comment] 2023-03-22 15:17
> I have no ARM computer and Github actions do not provide ARM runners AFAIK.
> 
> [flutter/flutter#74929](https://github.com/flutter/flutter/issues/74929)

Flutter itself does not support arm64 linux, but there are well-known third-party support
https://github.com/sony/flutter-elinux

But when I use flutter-elinux to compile, there are many scrolling errors, like this

> lib/main.dart:6:8: Error: Error when reading 'lib/gen/strings.g.dart': No such file or directory
> import 'package:localsend_app/gen/strings.g.dart';
> 
> lib/pages/tabs/settings_tab.dart:192:18: Error: The getter 't' isn't defined for the class
> '_SettingsTabState'.

I don't know if it's because of my environment configuration, because of the arm64 platform, or because this project is not compatible with arm. Looking forward to someone can perfect it.

**Comment by Tienisto** [comment] 2023-03-22 15:24
@kero990 Lots of Flutter apps rely on code generation. You need to generate them first: `flutter pub run build_runner build -d`

**Comment by kero990** [comment] 2023-04-05 14:54
> @kero990许多 Flutter 应用程序都依赖于代码生成。您需要先生成它们：`flutter pub run build_runner build -d`
I tried to compile successfully in x86 environment before attempting arm
I have not been able to compile successfully under x86, and the current error is as follows. I don't seem to have found the same issue in the search.

> ERROR: ../.pub-cache/hosted/pub.flutter-io.cn/extended_image-7.0.2/lib/src/gesture/page_view/widgets/scroll_position.dart:214:15: Error: The method 'ExtendedPagePosition.copyWith' doesn't have the named parameter 'devicePixelRatio' of overridden method 'ViewportOffset with ScrollMetrics.copyWith'.
> ERROR:   PageMetrics copyWith({
so many like this.....
and next is...

> ERROR: lib/pages/receive_page.dart:169:85: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
> ERROR:                                               Clipboard.setData(ClipboardData(text: _message)),
> ERROR:                                                                                     ^
> ERROR: lib/pages/receive_page.dart:29:11: Context: '_message' refers to a property so it couldn't be promoted.
> ERROR: See http://dart.dev/go/non-promo-property
> ERROR:   String? _message;
> ERROR:           ^
> ERROR: lib/widget/copyable_text.dart:22:59: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
> ERROR:               await Clipboard.setData(ClipboardData(text: value));
> ERROR:                                                           ^
> ERROR: lib/widget/copyable_text.dart:8:17: Context: 'value' refers to a property so it couldn't be promoted.
> ERROR: See http://dart.dev/go/non-promo-property
> ERROR:   final String? value;
> ERROR:                 ^
> ERROR: ../.pub-cache/hosted/pub.flutter-io.cn/extended_image-7.0.2/lib/src/gesture/page_view/gesture_page_view.dart:21:49: Error: Required named parameter 'devicePixelRatio' must be provided.
> ERROR: final PageMetrics _testPageMetrics = PageMetrics(
> ERROR:                                                 ^
> ERROR: ../flutter/packages/flutter/lib/src/widgets/page_view.dart:266:3: Context: Found this candidate, but the arguments don't match.
> ERROR:   PageMetrics({
> ERROR:   ^^^^^^^^^^^
> ERROR: ../.pub-cache/hosted/pub.flutter-io.cn/extended_image-7.0.2/lib/src/gesture_detector/drag.dart:145:3: Error: The superclass, 'OneSequenceGestureRecognizer with DragGestureRecognizerMixin', has no unnamed constructor that takes no arguments.
> ERROR:   ExtendedDragGestureRecognizer({
> ERROR:   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ERROR: ../.pub-cache/hosted/pub.flutter-io.cn/extended_image-7.0.2/lib/src/gesture/page_view/widgets/scroll_position.dart:222:23: Error: Required named parameter 'devicePixelRatio' must be provided.
> ERROR:     return PageMetrics(
> ERROR:                       ^
> ERROR: ../flutter/packages/flutter/lib/src/widgets/page_view.dart:266:3: Context: Found this candidate, but the arguments don't match.
> ERROR:   PageMetrics({
> ERROR:   ^^^^^^^^^^^
> ERROR: Target kernel_snapshot failed: Exception

**Comment by kero990** [comment] 2023-04-24 01:45
I reconfigured the environment and executed the above commands, and also attempted to use Flutter elinux. But the current errors for both are consistent.

I encountered a mismatch between the SDK and some dependency versions during construction, and I modified pubspec.yaml, but I am not sure if they will really work properly.

The current errors are as follows

> Compilation to SkSL failed.
> /root/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: GLSL to SPIRV failed;
> Compilation error. 3 error(s) and 1 warning(s).
> /root/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag: warning: (version,
> profile) forced to be (460, core), while in source code it is (320, es)
> /root/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:9: error: '#include' :
> Included file not found. for header name: flutter/runtime_effect.glsl
> /root/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error:
> 'FlutterFragCoord' : no matching overloaded function found
> /root/flutter-elinux/flutter/packages/flutter/lib/src/material/shaders/ink_sparkle.frag:93: error: '=' :
> cannot convert from ' const float' to ' temp 2-component vector of float'
> 
I have limited knowledge of Flutter, and my only interest is that I have a high-performance arm64 device. So now I can't determine if the problem is on Flutter, Flutter eLinux, or the project. I hope someone can give me some help.

**Comment by kero990** [comment] 2023-06-15 03:01
Latest progress
I reconfigured the flutter environment and the above bug has been fixed in flutter3.10.x

Now you can compile correctly with flutter-elinux, but it still won't work. The current error is as follows
```
flutter: Initializing tray failed: MissingPluginException(No implementation found for method InitSystemTray on channel flutter/system_tray/tray)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method ensureInitialized on channel window_manager)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308)
<asynchronous suspension>
#1      WindowManager.ensureInitialized (package:window_manager/src/window_manager.dart:91)
<asynchronous suspension>
#2      preInit (package:localsend_app/init.dart:88)
<asynchronous suspension>
#3      main (package:localsend_app/main.dart:28)
<asynchronous suspension>

```
Since the compilation has been successful, it is estimated that the compilation process can not be solved, looking forward to adapting the arm platform

**Comment by Tienisto** [comment] 2023-06-27 21:40
Seems like a bug in the window_manager package. I have no ARM64 Linux so I cannot reproduce it yet

**Comment by kero990** [comment] 2023-07-11 08:39
@Tienisto
Hi, I used a brand new Debian Docker to try compiling and running, and correctly switched the Flutter environment to 3.10.5. This time, the above error did not occur. Damn it, every one in this issues ended up being caused by the Flutter version, which makes me very unhappy.



Now there is only one final issue left, I seem to be unable to display my language (zh_CN) correctly. From the settings, the language configuration loading should be correct, and I guess there is no correct font to call. This may be related to the Linux version I am using, after all, the system of the arm64 device is diverse.

I don't know how localsend uses fonts on Linux or if it calls system fonts. I'm trying to copy some Chinese font files to/ Data/fluent_ Assets/fonts, but obviously invalid, I don't know the correct font file name.

Please help me solve this last step, thank you very much.

![](https://github.com/kero990/img/blob/main/%E6%88%AA%E5%9B%BE_localsend_app_20230711163254.png?raw=true)
![](https://github.com/kero990/img/blob/main/%E6%88%AA%E5%9B%BE_localsend_app_20230711163306.png?raw=true)

**Comment by Tienisto** [comment] 2023-07-11 10:02
@kero990 Glad that you managed to have a running version on ARM!

It seems that the default font doesn't support Chinese language correctly, you can try to change to another font in this file:

https://github.com/localsend/localsend/blob/main/lib/theme.dart#L82

The font just need to be installed on your system.

**Comment by rajesh-ut** [comment] 2023-08-04 04:14
> @Tienisto Hi, I used a brand new Debian Docker to try compiling and running, and correctly switched the Flutter environment to 3.10.5. This time, the above error did not occur. Damn it, every one in this issues ended up being caused by the Flutter version, which makes me very unhappy.
> 
> Now there is only one final issue left, I seem to be unable to display my language (zh_CN) correctly. From the settings, the language configuration loading should be correct, and I guess there is no correct font to call. This may be related to the Linux version I am using, after all, the system of the arm64 device is diverse.
> 
> I don't know how localsend uses fonts on Linux or if it calls system fonts. I'm trying to copy some Chinese font files to ./ Data/fluent_ Assets/fonts, but obviously invalid, I don't know the correct font file name.
> 
> I am finally able to use localsend on arm Linux, after so many twists and turns and even bypassing Flutter-eLinux. Please help me solve this last step, thank you very much.
> 
> ![](https://github.com/kero990/img/blob/main/%E6%88%AA%E5%9B%BE_localsend_app_20230711163254.png?raw=true) ![](https://github.com/kero990/img/blob/main/%E6%88%AA%E5%9B%BE_localsend_app_20230711163306.png?raw=true)

Can you please share the build steps?

**Comment by kero990** [comment] 2023-09-05 01:40
> > @Tienisto Hi, I used a brand new Debian Docker to try compiling and running, and correctly switched the Flutter environment to 3.10.5. This time, the above error did not occur. Damn it, every one in this issues ended up being caused by the Flutter version, which makes me very unhappy.嗨，我使用了一个全新的 Debian Docker 来尝试编译和运行，并正确地将 Flutter 环境切换到 3.10.5。这一次，上述错误没有发生。该死的，这个问题中的每一个最终都是由 Flutter 版本引起的，这让我非常不开心。
> > Now there is only one final issue left, I seem to be unable to display my language (zh_CN) correctly. From the settings, the language configuration loading should be correct, and I guess there is no correct font to call. This may be related to the Linux version I am using, after all, the system of the arm64 device is diverse.现在只剩下一个问题了，我似乎无法正确显示我的语言（zh_CN）。从设置中，语言配置加载应该是正确的，我想没有正确的字体可以调用。这可能与我使用的Linux版本有关，毕竟arm64设备的系统是多种多样的。
> > I don't know how localsend uses fonts on Linux or if it calls system fonts. I'm trying to copy some Chinese font files to ./ Data/fluent_ Assets/fonts, but obviously invalid, I don't know the correct font file name.我不知道localsend如何在Linux上使用字体，或者它是否调用系统字体。我正在尝试将一些中文字体文件复制到./数据/fluent_资产/字体，但显然无效，我不知道正确的字体文件名。
> > I am finally able to use localsend on arm Linux, after so many twists and turns and even bypassing Flutter-eLinux. Please help me solve this last step, thank you very much.我终于能够在 arm Linux 上使用 localsend，经过如此多的曲折，甚至绕过 Flutter-eLinux。请帮我解决最后一步，非常感谢。
> > ![](https://github.com/kero990/img/blob/main/%E6%88%AA%E5%9B%BE_localsend_app_20230711163254.png?raw=true) ![](https://github.com/kero990/img/blob/main/%E6%88%AA%E5%9B%BE_localsend_app_20230711163306.png?raw=true)
> 
> Can you please share the build steps?你能分享一下构建步骤吗？



> > @Tienisto Hi, I used a brand new Debian Docker to try compiling and running, and correctly switched the Flutter environment to 3.10.5. This time, the above error did not occur. Damn it, every one in this issues ended up being caused by the Flutter version, which makes me very unhappy.嗨，我使用了一个全新的 Debian Docker 来尝试编译和运行，并正确地将 Flutter 环境切换到 3.10.5。这一次，上述错误没有发生。该死的，这个问题中的每一个最终都是由 Flutter 版本引起的，这让我非常不开心。
> > Now there is only one final issue left, I seem to be unable to display my language (zh_CN) correctly. From the settings, the language configuration loading should be correct, and I guess there is no correct font to call. This may be related to the Linux version I am using, after all, the system of the arm64 device is diverse.现在只剩下一个问题了，我似乎无法正确显示我的语言（zh_CN）。从设置中，语言配置加载应该是正确的，我想没有正确的字体可以调用。这可能与我使用的Linux版本有关，毕竟arm64设备的系统是多种多样的。
> > I don't know how localsend uses fonts on Linux or if it calls system fonts. I'm trying to copy some Chinese font files to ./ Data/fluent_ Assets/fonts, but obviously invalid, I don't know the correct font file name.我不知道localsend如何在Linux上使用字体，或者它是否调用系统字体。我正在尝试将一些中文字体文件复制到./数据/fluent_资产/字体，但显然无效，我不知道正确的字体文件名。
> > I am finally able to use localsend on arm Linux, after so many twists and turns and even bypassing Flutter-eLinux. Please help me solve this last step, thank you very much.我终于能够在 arm Linux 上使用 localsend，经过如此多的曲折，甚至绕过 Flutter-eLinux。请帮我解决最后一步，非常感谢。
> > ![](https://github.com/kero990/img/blob/main/%E6%88%AA%E5%9B%BE_localsend_app_20230711163254.png?raw=true) ![](https://github.com/kero990/img/blob/main/%E6%88%AA%E5%9B%BE_localsend_app_20230711163306.png?raw=true)
> 
> Can you please share the build steps?你能分享一下构建步骤吗？

In fact, the current use of Flutter on arm64 is no different from that of x86. As I mentioned above, all errors reported on this appeal issue come from using the wrong version of Flutter.

When I compile correctly, the entire process is exactly the same as other platforms.

I am confident in using flutter@3.10.5 Ability to compile projects normally

**Comment by wuzhaohui100** [comment] 2023-09-13 06:57
1、Add font library
$ ll assets/fonts/NotoSansCJK-Regular.ttc
2、Change file:pubspec.yaml
 93 flutter:
 94   uses-material-design: true
 95 
 96   assets:
 97     - assets/img/
 98     - assets/web/
 99     - assets/CHANGELOG.md
100 
101   fonts:
102     - family: NotoSansCJKsc
103       fonts:
104       - asset: assets/fonts/NotoSansCJK-Regular.ttc


3、Change file:lib/theme.dart
 46   } else {
 47     fontFamily = 'NotoSansCJKsc';
 48   }

According to the above configuration, I can display it normally on the arm64 architecture.
![image](https://github.com/localsend/localsend/assets/108720447/117c3357-987a-4012-9e65-168d9309735b)

**Comment by jayna37** [comment] 2023-11-01 19:38
Hi Tien, I could send you a Raspberry Pi 4 for free. Would you be interested in that / would that make it possible for you to provide aarch64 builds? Cheers.

**Comment by Tienisto** [comment] 2023-11-01 22:28
Thanks @jayna37 

I already have a mac with ARM so I should be able to virtualize this.
I actually tried to host a Github Runner on an ARM linux server with Hetzner but the Github Runner somehow didn't work.
This is actually my goal because almost all binaries are compiled on the CI, compiling them locally would require too much time to me.

**Comment by Tienisto** [comment] 2023-11-05 23:13
I tried out to use ARM64 on the temporary sever but there is no official Flutter binary.

https://docs.flutter.dev/release/archive?tab=linux

@proletarius101 @kero990 @wuzhaohui100 have you compiled the Flutter engine yourself?

**Comment by oopen** [comment] 2023-11-06 06:23
> I tried out to use ARM64 on the temporary sever but there is no official Flutter binary.
> 
> https://docs.flutter.dev/release/archive?tab=linux
> 
> @proletarius101 @kero990 @wuzhaohui100 have you compiled the Flutter engine yourself?

Maybe use Docker image ? [fischerscode/flutter](https://hub.docker.com/r/fischerscode/flutter)

**Comment by kero990** [comment] 2023-11-07 08:59
I have uploaded an arm64 compilation file on Github for everyone to test if it can be used.

https://github.com/kero990/my_html/raw/master/localsend_1.10.0_linux_arm64.tar.gz

But I must clarify that when using this version, some images failed to be transmitted and cannot be opened after transmission. I am not sure if it is a problem with the arm64 platform or just the version.

I am researching the use of Flutter cross compilation to compile arm64 programs on the x86 platform, and can further use github action scripts to automatically generate them.
@jayna37 @LeisureLinux @Tienisto

**Comment by kero990** [comment] 2023-11-08 05:25
> I tried out to use ARM64 on the temporary sever but there is no official Flutter binary.我尝试在临时服务器上使用 ARM64，但没有官方的 Flutter 二进制文件。
> 
> https://docs.flutter.dev/release/archive?tab=linux
> 
> @proletarius101 @kero990 @wuzhaohui100 have you compiled the Flutter engine yourself?你自己编译过 Flutter 引擎吗？

The Flutter engine does not require compilation, and the so-called release has no architectural limitations. It is just a script file. You can download and extract the official compressed package, extract it anywhere and add the $PATH environment variable, or the git clone official repository. In short, it works no different from x64, although the official link states that the architecture is x64.

```
~$ which flutter
/opt/runtime/flutter/bin/flutter
~$ file /opt/runtime/flutter/bin/flutter
/opt/runtime/flutter/bin/flutter: Bourne-Again shell script, ASCII text executable
```

**Comment by kero990** [comment] 2023-11-08 05:41
@Tienisto 
In addition, I found the option of cross compilation in Flutter's cli help, but there are no tutorials available on the entire network, and it seems to require a sysroot for cross compilation. You can give it a try and perhaps write the compilation script for github actions directly.
```
$ flutter build linux --help
Build a Linux desktop application.

Global options:
-h, --help                  Print this usage information.
-v, --verbose               Noisy logging, including all shell commands executed.
                            If used with "--help", shows hidden options. If used with "flutter doctor", shows
                            additional diagnostic information. (Use "-vv" to force verbose logging in those
                            cases.)
-d, --device-id             Target device id or name (prefixes allowed).
    --version               Reports the version of this tool.
    --suppress-analytics    Suppress analytics reporting for the current CLI invocation.
    --disable-telemetry     Disable telemetry reporting each time a flutter or dart command runs, until it is
                            re-enabled.
    --enable-telemetry      Enable telemetry reporting each time a flutter or dart command runs.

Usage: flutter build linux [arguments]
-h, --help                                                   Print this usage information.
    --debug                                                  Build a debug version of your app.
    --profile                                                Build a version of your app specialized for
                                                             performance profiling.
    --release                                                Build a release version of your app (default mode).
    --[no-]obfuscate                                         In a release build, this flag removes identifiers
                                                             and replaces them with randomized values for the
                                                             purposes of source code obfuscation. This flag must
                                                             always be combined with "--split-debug-info"
                                                             option, the mapping between the values and the
                                                             original identifiers is stored in the symbol map
                                                             created in the specified directory. For an app
                                                             built with this flag, the "flutter symbolize"
                                                             command with the right program symbol file is
                                                             required to obtain a human readable stack trace.
                                                             
                                                             Because all identifiers are renamed, methods like
                                                             Object.runtimeType, Type.toString, Enum.toString,
                                                             Stacktrace.toString, Symbol.toString (for constant
                                                             symbols or those generated by runtime system) will
                                                             return obfuscated results. Any code or tests that
                                                             rely on exact names will break.
    --split-debug-info=<v1.2.3/>                             In a release build, this flag reduces application
                                                             size by storing Dart program symbols in a separate
                                                             file on the host rather than in the application.
                                                             The value of the flag should be a directory where
                                                             program symbol files can be stored for later use.
                                                             These symbol files contain the information needed
                                                             to symbolize Dart stack traces. For an app built
                                                             with this flag, the "flutter symbolize" command
                                                             with the right program symbol file is required to
                                                             obtain a human readable stack trace.
                                                             This flag cannot be combined with "--analyze-size".
    --[no-]tree-shake-icons                                  Tree shake icon fonts so that only glyphs used by
                                                             the application remain.
                                                             (defaults to on)
    --[no-]analyze-size                                      Whether to produce additional profile information
                                                             for artifact output size. This flag is only
                                                             supported on "--release" builds. When building for
                                                             Android, a single ABI must be specified at a time
                                                             with the "--target-platform" flag. When building
                                                             for iOS, only the symbols from the arm64
                                                             architecture are used to analyze code size.
                                                             By default, the intermediate output files will be
                                                             placed in a transient directory in the build
                                                             directory. This can be overridden with the
                                                             "--code-size-directory" option.
                                                             This flag cannot be combined with
                                                             "--split-debug-info".
    --code-size-directory                                    The location to write code size analysis files. If
                                                             this is not specified, files are written to a
                                                             temporary directory under the build directory.
    --dart-define=<foo=bar>                                  Additional key-value pairs that will be available
                                                             as constants from the String.fromEnvironment,
                                                             bool.fromEnvironment, and int.fromEnvironment
                                                             constructors.
                                                             Multiple defines can be passed by repeating
                                                             "--dart-define" multiple times.
    --dart-define-from-file=<use-define-config.json|.env>    The path of a .json or .env file containing
                                                             key-value pairs that will be available as
                                                             environment variables.
                                                             These can be accessed using the
                                                             String.fromEnvironment, bool.fromEnvironment, and
                                                             int.fromEnvironment constructors.
                                                             Multiple defines can be passed by repeating
                                                             "--dart-define-from-file" multiple times.
                                                             Entries from "--dart-define" with identical keys
                                                             take precedence over entries from these files.
    --[no-]pub                                               Whether to run "flutter pub get" before executing
                                                             this command.
                                                             (defaults to on)
-t, --target=<path>                                          The main entry-point file of the application, as
                                                             run on the device.
                                                             If the "--target" option is omitted, but a file
                                                             name is provided on the command line, then that is
                                                             used instead.
                                                             (defaults to "lib/main.dart")
    --[no-]track-widget-creation                             Track widget creation locations. This enables
                                                             features such as the widget inspector. This
                                                             parameter is only functional in debug mode (i.e.
                                                             when compiling JIT, not AOT).
                                                             (defaults to on)
    --build-number                                           An identifier used as an internal version number.
                                                             Each build must have a unique identifier to
                                                             differentiate it from previous builds.
                                                             It is used to determine whether one build is more
                                                             recent than another, with higher numbers indicating
                                                             more recent build.
                                                             On Android it is used as "versionCode".
                                                             On Xcode builds it is used as "CFBundleVersion".
                                                             On Windows it is used as the build suffix for the
                                                             product and file versions.
    --build-name=<x.y.z>                                     A "x.y.z" string used as the version number shown
                                                             to users.
                                                             For each new version of your app, you will provide
                                                             a version number to differentiate it from previous
                                                             versions.
                                                             On Android it is used as "versionName".
                                                             On Xcode builds it is used as
                                                             "CFBundleShortVersionString".
                                                             On Windows it is used as the major, minor, and
                                                             patch parts of the product and file versions.
    --target-platform                                        The target platform for which the app is compiled.
                                                             [linux-arm64 (default), linux-x64]
    --target-sysroot                                         The root filesystem path of target platform for
                                                             which the app is compiled. This option is valid
                                                             only if the current host and target architectures
                                                             are different.
                                                             (defaults to "/")

Run "flutter help" to see global options.
```

**Comment by jayna37** [comment] 2023-11-08 21:56
On my Fedora system:
```
$ ./localsend_app 
./localsend_app: error while loading shared libraries: libayatana-appindicator3.so.1: cannot open shared object file: No such file or directory
```
Could not find a package to install that provides it.

**Comment by Tienisto** [comment] 2023-11-09 00:43
Thanks @kero990 , I will look into this.

@jayna37, LocalSend requires `libayatana-appindicator3` to run

**Comment by kero990** [comment] 2023-11-09 08:49
> Thanks @kero990 , I will look into this.谢谢，我会调查这个。
No need, I tried and the result shows that cross compilation is still not supported. It seems that we still need to try compiling in the local environment. There are some Github actions that utilize Docker or QEMU cross compilation, although their performance is poor, they should at least be usable.

**Comment by jayna37** [comment] 2023-11-09 20:43
Thank you. Apparently Fedora does not package this library at all. Bummer but that's what it is.
https://github.com/neutralinojs/neutralinojs/issues/840

**Comment by Tienisto** [comment] 2023-12-05 02:00
There are now ARM64 binaries in `v1.13.0`.

I also have notices font issues but I think that's a separate issue.

**Closed by Tienisto** 2023-12-05 02:00 UTC
Labels: enhancement, help wanted
