### ISSUE TITLE
[Feature request] A way to send files using "open with" and "share" option in Windows

### ISSUE THREAD

**Issue by Marko-98** [localsend/localsend#1065] opened 2023-12-27 16:59 UTC
### Is your feature request related to a problem? Please describe.

Currently, if I want to send a file to my other device, I have to launch LocalSend and select the file which I want to send.

### Describe the solution you'd like

It would be much, much easier if I could just right click on the file, select "open with..." and "share". Then I'd just need to select device I want to send the file and that's it.

![Screenshot_1](https://github.com/localsend/localsend/assets/129692860/566f8f05-9e84-43e1-a0bf-7d95b1710909)
![Screenshot_2](https://github.com/localsend/localsend/assets/129692860/ae6ebede-9286-4097-b2d7-538ae72f19f3)

### Additional context

On Android there's already a way to do that. You just hold on file (or press three dots) and select share option. LocalSend will be one of the options. No need to go to the app to select the file like on Windows.

**Comment by Tienisto** [comment] 2024-01-01 21:40
Please checkout #528 before posting this issue.

Duplicate of #115

**Closed by Tienisto** 2024-01-01 21:40 UTC
