### ISSUE TITLE
use microsoft yh as default chinese font

### ISSUE THREAD

**Issue by sceraser** [localsend/localsend#150] opened 2023-02-11 18:19 UTC
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/42718757/218274607-678a3003-b809-4760-9078-add6b82489fc.png)
ugly chinese font with different font weight

### Describe the solution you'd like

use microsoft yh as default chinese font

**Comment by Tienisto** [comment] 2023-02-12 01:12
Duplicate of #52

**Closed by Tienisto** 2023-02-12 01:12 UTC
