### ISSUE TITLE
optional 'keep original metadata during file transfer'

### ISSUE THREAD

**Issue by geronimose** [localsend/localsend#1013] opened 2023-12-08 15:45 UTC
### Is your feature request related to a problem? Please describe.

I noticed the time stamp of the transferred file is the moment of creation on the destination, not the original time stamp.

### Describe the solution you'd like

Is it possible to add an optional feature that includes the metadata (such as time stamp and permissions) of the original file(s) with the transferred file(s)?

**Comment by Tienisto** [comment] 2023-12-08 23:09
Timestamp is feasable but updating permissions is not possible without elevated permissions I guess.

Duplicate of #650

**Closed by Tienisto** 2023-12-08 23:09 UTC
