### ISSUE TITLE
Add LocalSend to the Windows Explorer right-click "Send To" menu

### ISSUE THREAD

**Issue by fffelix-jan** [localsend/localsend#1422] opened 2024-06-18 02:08 UTC
### Is your feature request related to a problem? Please describe.

It is inconvenient to manually open LocalSend and drag in the file. For Bluetooth File Transfer, you can just right click the file and select the Bluetooth option in the Send To menu. LocalSend should be added to the menu just like Bluetooth.

### Describe the solution you'd like

Add LocalSend to the Windows Explorer right-click "Send To" menu

### Describe alternatives you've considered

Manually opening LocalSend, but it is inconvenient.

**Comment by Tienisto** [comment] 2024-06-18 11:35
Duplicate of #115

**Closed by Tienisto** 2024-06-18 11:35 UTC
