### ISSUE TITLE
Feature request: We can send a command line and the receiver executes the command

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [localsend/localsend#1355] opened 2024-05-21 08:51 UTC
### Is your feature request related to a problem? Please describe.

.

### Describe the solution you'd like

Add a sendable category: command
The receiver needs to call the shell to execute the command

### Describe alternatives you've considered

ssh or (sshpass and pssh)

**Comment by Tienisto** [comment] 2024-05-22 15:33
Duplicate of #11

**Closed by Tienisto** 2024-05-22 15:33 UTC
