### ISSUE TITLE
能不能添加一下iPhone自带的分享，好像是 Flutter iOS extension 

### ISSUE THREAD

**Issue by cheesewang1** [localsend/localsend#1059] opened 2023-12-23 05:40 UTC
### Is your feature request related to a problem? Please describe.

每次分享都得打开软件，要是可以直接系统分享唤起就好了

### Describe the solution you'd like

每次分享都得打开软件，要是可以直接系统分享唤起就好了

**Comment by cheesewang1** [comment] 2023-12-23 05:45
![54651C29-EB18-4D3A-A5CB-30D4E773AB9D](https://github.com/localsend/localsend/assets/153839220/3dc1e1d7-00c8-46f9-a8c1-794dd1b624c5)
![F2192BD4-02B3-4D60-B501-B4631E4C51D7](https://github.com/localsend/localsend/assets/153839220/26510bed-0918-4b0c-be9e-c062819b7034)

**Comment by cheesewang1** [comment] 2023-12-23 05:46
图片
![Uploading 2DFD758E-6946-4349-8F70-966EA0674105.jpeg…]()

**Comment by cheesewang1** [comment] 2023-12-23 05:46
![97B66ADA-8695-4CEB-A559-3F431482E72D](https://github.com/localsend/localsend/assets/153839220/6f93507e-4e3c-4e5a-be15-0c6fb97e98be)

**Comment by cheesewang1** [comment] 2023-12-23 05:48
![Uploading F116AC62-AE33-4FB9-8808-6E3D8F0F9CC5.jpeg…]()

**Comment by cheesewang1** [comment] 2023-12-23 05:50
![2C822086-4F6C-4029-B0EE-B38438EEB91C](https://github.com/localsend/localsend/assets/153839220/a5d65cbf-3cd4-4fe3-b38a-6bee298995eb)
![82E8BBB9-EB9E-41C6-9938-8016971716D5](https://github.com/localsend/localsend/assets/153839220/5f7835c3-8ecd-4ddb-9b43-7957656dae69)

**Comment by Tienisto** [comment] 2024-01-01 21:44
Please be aware that this is already supported on newer iOS versions.

Duplicate of #410

**Closed by Tienisto** 2024-01-01 21:44 UTC

**Comment by cheesewang1** [comment] 2024-01-02 02:41
没有支持iOS15版本吗，软件已经是最新的1.13.2(43)

**Comment by cheesewang1** [comment] 2024-01-02 02:43
我是iOS15.7
