### ISSUE TITLE
Upload Speed Limitation Compared to Alternative Solutions

### ISSUE THREAD

**Issue by EmircanKoc1** [localsend/localsend#1975] opened 2024-10-30 11:16 UTC
### Describe the bug

I have noticed that LocalSend artificially limits the upload speed during file transfers, while alternative file-sharing applications do not impose such restrictions. This limitation affects the overall transfer performance and user experience.

### To reproduce

Upload speed is being limited during file transfers (2.6 / 2.7 / 2.8 Mbps Maximum)
Comparison: Other similar applications allow full network speed utilization (For example snapdrop its uses full of network speed)
Impact: Slower file transfers than necessary, especially for large files

### Expected behavior
 Upload speed should utilize the maximum available network capacity
.

### Screenshots

.

### Desktop (please complete the following information)

LocalSend version: 1.15.4
Operating System: Windows 11
Network: Local network connection

### Smartphone (please complete the following information)

.

### Additional context

.

**Comment by Tienisto** [comment] 2024-10-30 12:09
Currently, you need to disable encryption on all devices to achieve maximum file speed. Duplicate of #384
There might be an improvement in the next version (1.16.0)

**Closed by Tienisto** 2024-10-30 12:09 UTC
