### ISSUE TITLE
Bug report: LocalSend window launches (visibly) on start-up despite the Hidden toggle being checked

### ISSUE THREAD

**Issue by tekspert** [localsend/localsend#1818] opened 2024-09-25 20:33 UTC
### Describe the bug

App won't start minimised in the tray bar.

### To reproduce

I have LocalSend set to "Autostart after login." However, I also have the "Start hidden" toggle checked.
The app is NOT launching Hidden and I have to close the window each time I login manually.

### Expected behavior

I expect LocalSend to launch minimised or close itself and stay open in the tray bar so the client is still discoverable.

### Screenshots

![image](https://github.com/user-attachments/assets/62f12d0f-e33a-4a1a-bebd-4e9030d07cde)

### Desktop (please complete the following information)

Windows 11 Home 23H2
LocalSend 1.15.4 (54)

### Additional context

This bug only appeared after I re-installed (updated) the program. There only appears to be one copy of LocalSend on the machine, and one start-up task.

**Comment by Tienisto** [comment] 2024-09-25 21:16
Can you disable and enable autostart and start hidden again?

**Comment by David-Ramboy** [comment] 2024-09-27 09:36
Can you give me scenario how you re-installed the app, maybe make sure to uninstall first the old program where there a pop mode that says delete all components or you should try to uninstall the localsend app then download https://github.com/localsend/localsend/releases/tag/v1.15.4 this and install it.

**Comment by tekspert** [comment] 2024-09-27 18:43
Like my other apps, I simply went to GitHub and executed the latest installer without removing the original LocalSend on my machine first. I have tried toggling off and on start-up, but I will try to purge LocalSend and re-install it fresh now.


------ Original Message ------
From "David Bryan Ramboy" ***@***.******@***.***>>
To "localsend/localsend" ***@***.******@***.***>>
Cc "David M 💯" ***@***.***>; "Author" ***@***.******@***.***>>
Date 27/09/2024 10:37:07
Subject Re: [localsend/localsend] Bug report: LocalSend window launches (visibly) on start-up despite the Hidden toggle being checked (Issue #1818)


Can you give me scenario how you re-installed the app, maybe make sure to uninstall first the old program where there a pop mode that says delete all components or you should try to uninstall the localsend app then download https://github.com/localsend/localsend/releases/tag/v1.15.4 this and install it.

**Comment by David-Ramboy** [comment] 2024-09-28 03:40
Yeah let me know if its works Thanks 😄

**Comment by tekspert** [comment] 2024-09-28 18:49
Fresh installing worked. Thanks for the advice 😊


------ Original Message ------
From "David Bryan Ramboy" ***@***.******@***.***>>
To "localsend/localsend" ***@***.******@***.***>>
Cc "David M 💯" ***@***.***>; "Author" ***@***.******@***.***>>
Date 28/09/2024 04:40:37
Subject Re: [localsend/localsend] Bug report: LocalSend window launches (visibly) on start-up despite the Hidden toggle being checked (Issue #1818)


Yeah let me know if its works Thanks 😄

**Comment by David-Ramboy** [comment] 2024-09-29 03:41
@Tienisto This issue has been resolved.

**Comment by David-Ramboy** [comment] 2024-09-29 03:55
@Tienisto It seems this issue was caused by not uninstalling the old version of the app before installing the new one. This can lead to old components remaining intact, which might cause issues. Based on this, I believe the problem is resolved. Could you please close the issue?

**Comment by Tienisto** [comment] 2024-09-29 21:51
There was a change from 1.14 to 1.15 that might cause some troubles

**Closed by Tienisto** 2024-09-29 21:51 UTC
