### ISSUE TITLE
No option to start hidden upon login

### ISSUE THREAD

**Issue by Salzman-Software** [localsend/localsend#1400] opened 2024-06-06 19:58 UTC
### Is your feature request related to a problem? Please describe.

you can't start the app hidden when logging in

### Describe the solution you'd like

add said option

**Comment by Tienisto** [comment] 2024-06-06 20:06
Do you use macOS? If yes, then it is likely a duplicate of #1242

**Closed** 2024-07-18 13:47 UTC
