### ISSUE TITLE
High occupancy of independent Graphics card

### ISSUE THREAD

**Issue by AlexanderDash** [localsend/localsend#596] opened 2023-07-31 17:47 UTC
### Describe the bug

When the rotatable sphere, namely the receiving interface, is minimized to the tray, you can see in the Task manager that the independent video card, RTX 3070, occupies 10% of the total. When I minimize the sending and setting interface to the tray, it will not occupy

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

fix bug

**Comment by Tienisto** [comment] 2023-07-31 17:49
This is a known bug. You need to switch to the settings tab.

Duplicate of #510

**Closed by Tienisto** 2023-07-31 17:49 UTC
