### ISSUE TITLE
I have a lot of things I want you to improve

### ISSUE THREAD

**Issue by bearcloney** [localsend/localsend#192] opened 2023-02-22 05:53 UTC
### Is your feature request related to a problem? Please describe.

1.[pc] The minimized icon in the lower right corner should be changed to: left click to open directly, right click to pop up options

2.[pc] Add shortcut send in the right-click menu

3.[pc, android] When there is one device connected, it will be sent directly without confirming the device. When the device is larger than one or there is no device, a pop-up window will appear to select the device

4.[pc, android] After sending "A" file and then sending "B" file, you need to delete the previously added a, I think you need a switch that does not keep the history added

5.[pc, android] show real-time transfer speed

6.[android] Android client save location can be set

### Describe the solution you'd like

The software looks good overall, but many functions are still unsatisfactory

**Comment by Tienisto** [comment] 2023-02-24 12:26
5. Real time speed is always shown as soon as 5 MB has been sent, the speed is too volatile for small transfers.

**Comment by Tienisto** [comment] 2023-03-05 13:29
1. Added in `v1.8.0`
2. Duplicate of #115 
3. I don't know if this is confusing / unexpected behaviour
4. Added in `v1.8.0`
5. See previous comment
6. This is technically difficult because of the new scoped storage permissions.

**Closed by Tienisto** 2023-03-05 13:29 UTC
Labels: enhancement

**Comment by Tienisto** [comment] 2023-03-15 23:38
@zillydev You are right. Created #293
