### ISSUE TITLE
Feature request: support wifi direct to accelerate transfer

### ISSUE THREAD

**Issue by RUV2005** [localsend/localsend#1069] opened 2023-12-30 15:54 UTC
### Is your feature request related to a problem? Please describe.

like `Zapya`  ,it use `wifi direct` , the transmission speed reaches an astonishing 100M/s instead of 10M/s.

### Describe the solution you'd like

support wifi direct

**Comment by RUV2005** [comment] 2024-01-01 02:41
Yesterday, I used Zapya continuously transferred **2000 files**, The total file size has reached **126GB**,Before this, I tried using Localsend, but the speed could only reach **10MB/S** or even lower, with an estimated transfer time of **3.5 hours**. 
Then, I used Zapya for file transfer. When I started, its transfer speed was **50-100MB/S**, with an estimated transfer time of only about **40 minutes** and **support for breakpoint continuation**. 
I believe that **WIFI direct** connection greatly improves the efficiency of file transfer

**Comment by Tienisto** [comment] 2024-01-01 21:39
Wifi Direct is of course better but this is hard to implement (correctly).

Duplicate of #189

**Closed by Tienisto** 2024-01-01 21:39 UTC
