### ISSUE TITLE
Fails to Install on Windows ARM devices

### ISSUE THREAD

**Issue by powyncify** [localsend/localsend#1550] opened 2024-07-22 09:55 UTC
### Describe the bug

Windows devices on ARM processors, like the Microsoft Surface Snapdragon, are ever more popular. We'd like to run this wonderful piece of software on our devices, but can't install it due to an error message.

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Installation completed successfully 

### Screenshots

<img width="335" alt="local send 2024-07-22_11-49" src="https://github.com/user-attachments/assets/ddbc94f8-aaa2-47df-b4e8-3d8803218e9f">

### Desktop (please complete the following information)

Windows 11

**Comment by Tienisto** [comment] 2024-07-22 09:58
Duplicate of #1540

**Closed by Tienisto** 2024-07-22 09:58 UTC
