### ISSUE TITLE
Feature request  Please ！！！Developed the HarmonyOS NEXT version

### ISSUE THREAD

**Issue by mengliwunian** [localsend/localsend#1887] opened 2024-10-11 02:53 UTC
### Is your feature request related to a problem? Please describe.

HarmonyOS NEXT has been in public beta, please help develop the HarmonyOS NEXT version

### Describe the solution you'd like

No response

**Comment by Tienisto** [comment] 2024-10-11 11:00
Duplicate of #1885

**Closed by Tienisto** 2024-10-11 11:00 UTC
