### ISSUE TITLE
Bug report: nearby devices can't pair in the same network

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [localsend/localsend#196] opened 2023-02-22 20:13 UTC
### Describe the bug

My WiFi network is configured bit different with static IPv4 for each device type.
For example, my computers/laptops are located at 192.168.1.xx, phones at 192.168.2.xx.

network: 192.168.x.x
gateway: 192.168.0.1
mask: 255.255.0.0

### Case 1
PC - 192.168.1.2
Phone - 192.168.1.43
Result: two devices find each other when you press refresh button

### Case 1
PC - 192.168.1.2 (PC#2 in network dot 1)
Phone - 192.168.2.1 (Phone#1 in network dot 2)
Result: two devices can't find each other but they are located in the same network

### To reproduce

1. make sure you know how to set up static IPv4 in your router
2. try to use case 1
3. try to use case 2
4. see the difference

### Expected behavior

The devices are on the same local network, but it looks like your software does not understand that 192.168.1.xx and 192.168.2.xx is the same network

### Case 1
![case1](https://user-images.githubusercontent.com/109800286/220747745-1012b804-2ae0-4433-b7d2-725955d428a7.png)
### Case 2
![case2](https://user-images.githubusercontent.com/109800286/220748521-5b7f7689-7df6-4a0b-b105-369d03cc6ed8.png)

### Desktop (please complete the following information)

- OS: Windows 11
- Version: 1.7.0

### Smartphone (please complete the following information)

- Device: Xiaomi Redmi Note 7
- OS: AOSP firmware, Android 10
- Version: 1.7.0

**Comment by EsuRt** [comment] 2023-02-24 03:18
Same problem.

**Comment by Tienisto** [comment] 2023-02-25 15:26
Duplicate of #175

**Closed by Tienisto** 2023-02-25 15:26 UTC
