### ISSUE TITLE
File transfer/receipt is not possible starting from version 1.15.

### ISSUE THREAD

**Issue by PerryLayne** [localsend/localsend#1554] opened 2024-07-23 19:00 UTC
### Describe the bug

PathAccessException: Cannot open file, path = '/storage/emulated/0/【test】/Localsend/Localsend.apk' (OS Error: Operation not permitted, errno = 1)

### To reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Starting from version 1.15 (Google Play version), when transferring files from Windows to an Android phone (Xiaomi), if the destination is not the Download folder (the default folder), the transfer will fail at the end. This issue does not occur in the Android version (GitHub) before 1.15.

The error is approximately as follows:

### Smartphone (please complete the following information)

Xiaomi 14 Pro - HyperOS -1.0.45.0

**Comment by Tienisto** [comment] 2024-07-23 19:25
Create a custom folder inside the Download directory or wait for the next bug fix release.

Duplicate of #1544

**Closed by Tienisto** 2024-07-23 19:25 UTC

**Comment by Garphy** [comment] 2024-11-04 13:02
dame! That's the problem after Android newest patch...
