### ISSUE TITLE
Feature request: Save Networks, Save Devices & Save Devices for QuickSend

### ISSUE THREAD

**Issue by trymeouteh** [localsend/localsend#282] opened 2023-03-12 00:51 UTC
### Is your feature request related to a problem? Please describe.

The ability to save networks, devices and the ability to save which devices will allow QuickSend with.

### Describe the solution you'd like

A menu to manager saved network

A menu to manage saved devices
A menu to label saved devices (Mom's iPhone, My Laptop, etc)

A menu to manage which devices will allow QuickSend (For trusted devices)

**Comment by Tienisto** [comment] 2023-03-12 00:54
Duplicate of #7

**Closed by Tienisto** 2023-03-12 00:54 UTC
