### ISSUE TITLE
Specify the network card to open the port

### ISSUE THREAD

**Issue by sidottu** [localsend/localsend#2163] opened 2024-12-26 14:07 UTC
How can I configure localsend in Windows 10 to avoid using the ports of a specific network card while keeping the internet connection on that card active? As shown in the image, I do not want the software to use the ports of the public IP (123.456.123.456) obtained from the dial-up connection; I want it to use the LAN IPs of my other two network cards (Wi-Fi with IP 10.10.x.x and Ethernet with IP 192.168.x.x) for file transfers. I can't seem to find the relevant settings.

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/50bc72f1-d71c-47f9-8be8-18043a57b7f5)
Make PPPoE （123.456.123.456）not appear here

**Comment by Tienisto** [comment] 2024-12-26 23:05
Duplicate of #1538

**Closed by Tienisto** 2024-12-26 23:05 UTC
