### ISSUE TITLE
[Feature request] Windows right click context menu shortcut

### ISSUE THREAD

**Issue by bibsp** [localsend/localsend#1364] opened 2024-05-23 04:43 UTC
### Is your feature request related to a problem? Please describe.

Can you please add a **LocalSend** shortcut in File/Folder's right click context menu? It will be easier to send files and folder directly from windows file explorer.

### Describe the solution you'd like

I want a **LocalSend** shortcut here.
![Screenshot (75)](https://github.com/localsend/localsend/assets/98865389/85394ab4-ce5e-46cd-ba30-f9451434835a)
![Screenshot (76)](https://github.com/localsend/localsend/assets/98865389/11f6e5c6-4990-47d9-935b-42379e7d02b7)

**Comment by Tienisto** [comment] 2024-05-23 09:04
Duplicate of #115

**Closed by Tienisto** 2024-05-23 09:04 UTC
