### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by WorldOfWheat** [localsend/localsend#264] opened 2023-03-10 12:47 UTC
### Describe the bug

I can't start the program, and I use portable version on Windows 7.

### To reproduce

1. Go to 'LocalSend folder'
2. Click on 'localsend_app.exe'
3. See error

### Expected behavior

I except to start the LoaclSend.

### Screenshots

Problem signature:
  Problem Event Name:    APPCRASH
  Application Name:    localsend_app.exe
  Application Version:    1.7.0.26
  Application Timestamp:    63ea0851
  Fault Module Name:    ucrtbase.DLL
  Fault Module Version:    10.0.14393.2247
  Fault Module Timestamp:    5adc1d0b
  Exception Code:    40000015
  Exception Offset:    000000000006eacf
  OS Version:    6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1:    ea22
  Additional Information 2:    ea2237c461d39d64e726ee93ac56511c
  Additional Information 3:    34be
  Additional Information 4:    34be574f4cad6be67ce441734c327fc2

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

### Desktop (please complete the following information)

Windows 7

**Comment by Tienisto** [comment] 2023-03-10 13:50
Duplicate of #66

**Closed** 2023-03-10 13:50 UTC
