### ISSUE TITLE
Crash on large file amount

### ISSUE THREAD

**Issue by cd-FileX** [localsend/localsend#931] opened 2023-11-23 10:41 UTC
### Describe the bug

When sending large amounts of bigger files, the app crashes.

### To reproduce

1. Go to send
2. Click on 'Folder'
3. Select a folder with a lot of files, preferably bigger files (in my case 338, 1.1GB)
4. Crash

### Expected behavior

Loads and processes the files each single one so it is still responsive.

### Smartphone (please complete the following information)

- Redmi Note 10 JE
- Android 13, MUI 14.0.16
- Version 1.12.0 (38)

**Comment by Tienisto** [comment] 2023-11-23 16:16
Please use the search before opening new issues.

Duplicate of #907

**Closed by Tienisto** 2023-11-23 16:16 UTC
