### ISSUE TITLE
[Feature request] Customize frequently used IP addresses

### ISSUE THREAD

**Issue by lijinpeng1980** [localsend/localsend#190] opened 2023-02-22 02:38 UTC
### Is your feature request related to a problem? Please describe.

My PC's fixed IP address is 10.3.1.3

My mobile phone's fixed IP address is 10.203.1.3

Although they are not in the same network segment, automatic network scanning cannot find each other, but in fact they can communicate with each other. You only need to manually enter the IP address of the other party to transfer files.

But it is a little inefficient and annoying to manually enter the address of the other party every time.

I hope you can add customized frequently used client devices or IP addresses.

LocalSend is the best. Thank you very much.

### Describe the solution you'd like

![20230222101426](https://user-images.githubusercontent.com/18733229/220506859-0b3496cc-ed6c-4eb7-8c44-977c7bc2c9c3.png)

**Comment by Tienisto** [comment] 2023-03-06 19:53
Duplicate of #7

**Closed by Tienisto** 2023-03-06 19:53 UTC
