### ISSUE TITLE
"Select all" button(option) 

### ISSUE THREAD

**Issue by gitfifi** [localsend/localsend#492] opened 2023-05-30 15:46 UTC
### Is your feature request related to a problem? Please describe.

When selecting media, file etc to send, a "Select all" button(option) should be provided, otherwise, the selection process will make users crazy when sending hundreds of media or files.

### Describe the solution you'd like

just add a "Select all" button(option)

**Comment by jp1017** [comment] 2023-06-14 06:53
+1

**Comment by neil123495** [comment] 2023-08-25 12:24
+1

**Comment by Tienisto** [comment] 2023-08-25 13:20
Unfortunately, We cannot just add a "select all" option.
We need to use an entirely new picker instead.

Duplicate of #376

**Closed as not planned by Tienisto** 2023-08-25 13:20 UTC
Labels: duplicate, enhancement
