### ISSUE TITLE
Feature request(need ipv6 support)

### ISSUE THREAD

**Issue by 8423ffsf** [localsend/localsend#2109] opened 2024-12-01 08:15 UTC
### Is your feature request related to a problem? Please describe.

no,it doesn't relate to any bugs

### Describe the solution you'd like

the localsend can listen on the ipv6 port.

### Describe alternatives you've considered

none

**Comment by Toorero** [comment] 2024-12-10 00:47
Duplicate of #549

**Closed** 2024-12-10 03:06 UTC
