### ISSUE TITLE
JPG file's size is reduced and EXIF info is missing

### ISSUE THREAD

**Issue by CannedGrape** [localsend/localsend#302] opened 2023-03-19 02:51 UTC
### Describe the bug

Send photo from Windows PC to iPhone:
1. original photo is JPG format and its size is 4016*6016 **14.2**MB;
2. Quick Save is On; Save media to gallery is On;
3. after transfer, the photo size is reduced to 4016*6016 **3.3**MB, and all EXIF info is missing.

### To reproduce

1. original photo is JPG format and its size is 4016*6016 **14.2**MB;
2. Quick Save is On; Save media to gallery is On;
3. after transfer, the photo size is reduced to 4016*6016 **3.3**MB;

### Expected behavior

after transfer, the photo size and EXIF info are same as original photo.

### Desktop (please complete the following information)

PC: Win10

### Smartphone (please complete the following information)

iPhone 13, iOS:16.3.1

**Comment by Tienisto** [comment] 2023-03-20 22:38
Duplicate of #237

**Closed by Tienisto** 2023-03-20 22:38 UTC
