### ISSUE TITLE
[Feature request] Remember connected device.

### ISSUE THREAD

**Issue by hugeBlack** [localsend/localsend#250] opened 2023-03-07 07:36 UTC
### Is your feature request related to a problem? Please describe.

This app is so useful that I always use it to transfer files across platforms.
However, when I'm at school, devices cannot find each other even when they are in the same network, so I have to type in IP address of my devices every time to transfer files.

### Describe the solution you'd like

Add a "remembered devices" feature so that I can save IP address of all my devices since I seem to have a static nat IP address.
Whenever I want to send files to a device, I can simply choose the device in the remembered devices list without typing address all the time.

**Comment by Tienisto** [comment] 2023-03-07 10:09
Duplicate of #7

**Closed by Tienisto** 2023-03-07 10:09 UTC
