### ISSUE TITLE
Bug report: Windows autostart hidden not working

### ISSUE THREAD

**Issue by MEGAKek77** [localsend/localsend#1293] opened 2024-04-26 11:46 UTC
### Describe the bug

The setting "Autostart: Start hidden" isnt working on windows, it starts in the foreground.

### To reproduce

1. Go to Settings
2. Click on Autostart: Start hidden
3. Restart PC 
4. Program is autostarting in the foreground

### Expected behavior

Expected behavior: autostarting in the taskbar, not in the foreground on the desktop

### Desktop (please complete the following information)

Windows

**Comment by cr0eax** [comment] 2024-05-10 19:17
Investigated a bit.
Currently autorun registry key value looks like this:
`C:\Program Files\LocalSend\localsend_app.exe autostart`
When auto started by windows I can see that "autostart" argument is missing from command line.
After changing registry value to following, problem is fixed.
`"C:\Program Files\LocalSend\localsend_app.exe" autostart`
So, bug caused by space in the path.

I see multiple opened issues about this problem. Hope it finally gets fixed now.
https://github.com/localsend/localsend/issues/687
https://github.com/localsend/localsend/issues/1231
https://github.com/localsend/localsend/issues/464

**Comment by RPXbr** [comment] 2024-06-10 01:21
I created a quick solution in Windows until this bug is fixed. I hope this helps:

https://github.com/localsend/localsend/issues/464#issuecomment-2156997926

**Comment by davideaccogli** [comment] 2024-07-03 07:06
Changing registry value fixed the issue.
Please solve in next version

**Closed** 2024-07-09 16:45 UTC
