### ISSUE TITLE
automatic pairing need

### ISSUE THREAD

**Issue by Vanda688** [localsend/localsend#309] opened 2023-03-22 08:50 UTC
### Is your feature request related to a problem? Please describe.

Every time before transmission, the port number needs to be entered for pairing, which is a bit troublesome.

### Describe the solution you'd like

Is it possible to add a function for automatic pairing with permanent pairing information?Just like the "add to trusted devices" feature, this makes future transfers more convenient.

**Comment by Tienisto** [comment] 2023-03-24 20:51
Duplicate of #7

**Closed by Tienisto** 2023-03-24 20:51 UTC
