### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by luckyblue555** [localsend/localsend#269] opened 2023-03-11 11:28 UTC
### Is your feature request related to a problem? Please describe.

1. Could not use right-click menu on win10 to send files;
2. Could not choose saving folder for receiving files on android.

### Describe the solution you'd like

Suggest strongly to add following 2 featuers, then the apps will be much better:
1. To add LocalSend to right-click menu on win10 to send files;
2. User can choose  saving folder for receiving files on android.
Thanks so much!

**Comment by Tienisto** [comment] 2023-03-11 14:45
Please use the search to avoid duplicates. And don't join multiple issues into one issue.

Duplicate of #115 and #235

**Closed by Tienisto** 2023-03-11 14:45 UTC
