### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by TriDefender** [localsend/localsend#1819] opened 2024-09-26 12:42 UTC
### Is your feature request related to a problem? Please describe.

I'm always frustrated when you have to manualy send and receive clipboard, it lacks the seamless interdevice collaboration

### Describe the solution you'd like

I hope you can "pair“ a device and everything you copied on clipboard will be automatically moved over without manual confirmation.

### Describe alternatives you've considered

I have considered the my phone application on windows but it does not support regions outside china. plus it's closed source

**Comment by Tienisto** [comment] 2024-09-26 13:28
Duplicate of #163

**Closed by Tienisto** 2024-09-26 13:28 UTC
