### ISSUE TITLE
File select screen select button is too small

### ISSUE THREAD

**Issue by User65-87-11** [localsend/localsend#1641] opened 2024-08-14 04:56 UTC
### Describe the bug

In the file selection screen after selecting which files to send there is "select" clickable button in the top bar that is too small to miss unlike in the main menu when buttons are well spaces and padded.

### To reproduce

1.Go to send
2.Select files
3.see Select appears in the top bar
4.Small isn't  it?

### Expected behavior

4.Somewhat larger button

### Desktop (please complete the following information)

Android

**Comment by Tienisto** [comment] 2024-08-17 23:50
Duplicate of #376

**Closed by Tienisto** 2024-08-17 23:50 UTC

**Comment by User65-87-11** [comment] 2024-11-13 15:47
Was the button changed? Now its big enough! ty =)
