### ISSUE TITLE
Couldn't find my Cross-segment devices in 'nearby devices'

### ISSUE THREAD

**Issue by R3habDroid** [localsend/localsend#221] opened 2023-03-01 01:57 UTC
### Is your feature request related to a problem? Please describe.

Couldn't find my Cross-segment devices in 'nearby devices',need to input ip address every time.
like:
A device ip address = '192.168.13.1'
B devices ip address = '192.168.14.1'

### Describe the solution you'd like

1. Find a way to save a used device to 'nearby devices'.

2. Get a new tag 'recently used'.

so we don't need to input ip address every time.

**Comment by Tienisto** [comment] 2023-03-02 20:30
Duplicate of https://github.com/localsend/localsend/issues/199 , https://github.com/localsend/localsend/issues/175

**Closed by Tienisto** 2023-03-02 20:30 UTC

**Comment by JaosnHsieh** [comment] 2023-11-06 17:44
On my DLINK wifi router (DIR-2055 , HW:A1 , FW:1.11), I turned all firewall features off and localsend works for discovering and sending/receiving files!


![Screenshot 2023-11-06 at 12 41 50 pm](https://github.com/localsend/localsend/assets/15373520/6ed0ba91-3325-43c6-a599-742af1cbbee2)
