### ISSUE TITLE
not suport mac 10.15.7

### ISSUE THREAD

**Issue by CrazyJasonwell** [localsend/localsend#1289] opened 2024-04-25 08:12 UTC
### Describe the bug

the newest version not suport mac 10.15.7

### To reproduce

the newest version not suport mac 10.15.7

### Expected behavior

the newest version not suport mac 10.15.7

**Comment by Tienisto** [comment] 2024-04-25 11:02
Duplicate of #1200

**Closed by Tienisto** 2024-04-25 11:02 UTC
