### ISSUE TITLE
add webpage for receiving files

### ISSUE THREAD

**Issue by pokegamer5547** [localsend/localsend#863] opened 2023-11-03 05:06 UTC
### Is your feature request related to a problem? Please describe.

So far we can't receive files from an device which doesn't have localsend installed, which could be a problem when another user doesn't want to install localsend. 

### Describe the solution you'd like

The client, or i guess the main user who has localsend, could tell it to run a webserver which can be accessed to receive files instead. That way, we dont need to install localsend on other user device as long as we have it on our device. 

### Additional context

It's similar to how a software called [qrcp](https://github.com/claudiodangelis/qrcp) which creates a webserver when it comes to receiving files. tho i can't use it anymore due to some weird issues with go in android.

**Comment by Tienisto** [comment] 2023-11-03 11:12
Duplicate of #424

**Closed by Tienisto** 2023-11-03 11:12 UTC
