### ISSUE TITLE
SocketException: Failed to create server socket

### ISSUE THREAD

**Issue by muchqs** [localsend/localsend#1568] opened 2024-07-27 00:31 UTC
### Describe the bug

Android 14

After I updated to latest v1.15.2, I have this error. It's the exact same error shown in this screenshot
https://github.com/localsend/localsend/issues/176#issuecomment-1440654277

I uninstalled and reinstalled, first startup was fine. Then second startup this error showed again and server is offline.

Uninstalled and went back to v1.15.1, no error, no problem so far.

### To reproduce

1. install v1.15.2 and open
2. close and reopen v1.15.2
3. See error

### Expected behavior

no error

**Comment by Tienisto** [comment] 2024-07-27 01:16
The server logic hasn't been changed from 1.15.1 to 1.15.2 so I don't know what could be the cause

**Comment by Tienisto** [comment] 2024-07-27 01:35
What do you mean by "second run"? Do you open LocalSend manually or via share dialog? How did you install LocalSend (F-Droid, Apk)?

If you started LocalSend manually, do you see another instance of LocalSend by viewing the opened apps?

**Comment by gman414** [comment] 2024-07-27 04:33
Hi,
I am experiencing the same issue on my smartphone (Android 14) with Localsend 1.15.2
I had installed Localsend via Google Playstore.

The app runs fine  on the first launch but if you had exit the app by pressing the back button
and then all subsequent launches will result in "SocketExeception" error as described by the OP.

![Localsend](https://github.com/user-attachments/assets/bc68bce8-211b-4fc9-81ac-47fb6c7d8e08)



But if  Localsend is closed by clearing the "recent apps"  ( via the navigation button)  or if  force  stopped the and relaunched,  then Localsend opens without any such error.

**Comment by gagantk** [comment] 2024-07-27 08:06
Hey, even I'm facing the exact same issue on my Android 14, downloaded from Google Play Store today. This is the first time I'm installing LocalSend. Hope this gets fixed soon.

**Comment by cinmau** [comment] 2024-07-27 09:57
Hello, the same thing happens to me with Galaxy s 23 and Android 14. Before the latest update it always worked without problems.

**Comment by Tienisto** [comment] 2024-07-27 10:27
Alright, the "back" gesture was the trick!
The latest version (1.15.2) has multiple threads for the first time to off load discovery work. It seems that the secondary threads are not killed by the "back" gesture so that the main thread is still running waiting for them being killed

**Comment by cinmau** [comment] 2024-07-27 11:45
Tienisto,  thank you very much for your reply

**Closed** 2024-07-27 15:00 UTC
Labels: bug, android

**Comment by Tienisto** [comment] 2024-07-27 15:08
You can use https://github.com/localsend/localsend/releases/download/v1.15.2/LocalSend-1.15.2-android--fix-back-gesture.apk

if you want to have 1.15.2 right away. Otherwise, wait for the next release.

**Comment by cinmau** [comment] 2024-07-27 18:03
Tienisto, thank you very much

**Comment by gman414** [comment] 2024-07-27 22:07
Thank you for the fix

**Comment by Daaaaf** [comment] 2024-08-03 10:45
I have this exact issue in Windows 10... :/
