### ISSUE TITLE
500 Could not save file when Downloads folder is missing

### ISSUE THREAD

**Issue by 404service** [localsend/localsend#266] opened 2023-03-11 01:14 UTC
### Describe the bug

[500] Could not save file

### To reproduce

[500] Could not save file

### Expected behavior

[500] Could not save file

**Comment by Tienisto** [comment] 2023-03-11 01:17
What does the receiving device say?

**Comment by 404service** [comment] 2023-03-11 01:21
> 
![1678497678220](https://user-images.githubusercontent.com/127535964/224457009-3af54c80-29c4-4b07-b565-a0485dadcc24.png)

**Comment by 404service** [comment] 2023-03-11 01:23
Nothing happened after the mobile phone ran the progress bar.

**Comment by Tienisto** [comment] 2023-03-11 01:23
No, this is the sender. What does the receiver say?

**Comment by 404service** [comment] 2023-03-11 01:24
> 接收设备说什么？
Nothing happened after the mobile phone ran the progress bar.

**Comment by Tienisto** [comment] 2023-03-11 01:26
So you send from Windows to phone? And on the phone, there is no error?

**Comment by 404service** [comment] 2023-03-11 01:28
> 

Yes, the mobile phone just ran the progress bar, and the computer reported an error. I tried both computers.

**Comment by 404service** [comment] 2023-03-11 01:49
> 所以你从Windows发送到手机？在电话里，没有错误吗？
Found the problem. The mobile phone has no download folder, so it can't accept files. I hope I can optimize the mobile client in the future and let him build his own download folder.

**Comment by Tienisto** [comment] 2023-03-11 01:50
Thank you!

**Comment by xuqian2072** [comment] 2023-03-19 12:25
![Screenshot_2023-03-19-20-19-46-979_org localsend localsend_app](https://user-images.githubusercontent.com/80939886/226174759-4c26e459-bee6-4264-b8b0-3448f6ae3b17.jpg)
一样的错误从Windows发送到安卓设备出现，然后接收端出现了问题。

**Comment by xuqian2072** [comment] 2023-03-19 12:32
安卓设备是MIUI12/Android10，Windows设备为Win11。
安卓设备有Download文件夹，而且我已经授予了localsend访问所有文件的权限。

**Comment by xuqian2072** [comment] 2023-03-19 12:37
> Reference

软件版本是1.8.0

**Comment by BF233project** [comment] 2023-06-19 21:29
u cloud try open folder in localsend, see are u give the license to see android folder.
你尝试下从localsend的文件夹打开手机存储内的文件，这里如果你没给权限应该会提示的。这个权限相对比较隐蔽，给了之后就能收文件了

**Comment by Virgus** [comment] 2023-09-04 18:58
Hello, I've just downloaded the latest version (first use for me) and I tested it with two android phones with Lineage OS and two laptops with Windows 7. The transfer from Android to PC works like a charm but when going from the PCs to the Android phones this problem still occurs and I'm limited to use the Downloads folder on Android. I've read on the changelog that the problem was solved in version 1.10 
> fix(android): get downloads directory correctly (@Tienisto)

Might it be a Lineage OS issue that I'm still seeing this occurring ?
Could I do something enabling the privileges of the destination folder ?
I'm trying to use /storage/emulated/0/LocalSend as dest,

Thanks for this great tool !

**Comment by Tienisto** [comment] 2023-09-04 19:37
Does it work if you create a sub directory "LocalSend" inside the "Downloads" folder?

**Comment by Virgus** [comment] 2023-09-05 07:22
> Does it work if you create a sub directory "LocalSend" inside the "Downloads" folder?

I just tested and got this new error (repeated several times by swapping from Downloads which is working, to Downloads/LocalSend).

![20230905_091647_Snapshot_localsend_app](https://github.com/localsend/localsend/assets/6388217/fe995008-db61-48b9-b6be-bf2ccf4391be)

Please let me know if I could be of any help with further tests and in troubleshooting this issue.

**Comment by oamjz1939** [comment] 2023-09-05 08:14
#### can be reproduced by the following operations

1. Computer transfer any <u>file</u> to mobile phone
2. Move this <u>file</u> from the download directory to another folder on your phone
3. At this time, an error will occur if you transfer the same <u>file</u> to the mobile phone.

#### can be temporarily resolved in the following operations

1. Delete <u>file</u> in other folders
2. Restart the phone

------

#### 可以通过以下操作复现

1. 电脑传输任意<u>文件</u>至手机
2. 在手机上将此<u>文件</u>从下载目录移动至其他文件夹
3. 此时再传输同一个<u>文件</u>至手机就会出错

#### 可以通过以下方式暂时解决

1. 删除其他文件夹下的<u>文件</u>
2. 重启手机

**Comment by Faserr** [comment] 2023-10-12 14:14
I have encountered this issue as well. When I transfer between mobile apps, this error appears. When I use the link sharing feature, the download record of another device disappears after it is downloaded using Chrome. However, when I open the download directory using the file manager, the file has already been downloaded successfully.

**Comment by rxnwin** [comment] 2023-10-29 00:22
我在Android向mac发送文件时遇到了同样的报错信息，后在mac端的设置中重新修改了保存目录解决，虽然修改前后的目录位置都是一样的（桌面目录）

**Comment by MajorTooooom** [comment] 2023-11-10 07:35
同样的问题，[500] Could not save file，手机端权限都开了,手机能往电脑传成功，电脑往手机传提示 [500] Could not save file

**Comment by wonderhj** [comment] 2023-11-25 09:32
我遇到了同样的问题，我的手机是小米13，当电脑往手机传文件的时候出现 [500] Could not save file，当手机往电脑传的时候，点击媒体选了要传送的文件之后就退出来了，无法传送媒体。

**Closed** 2024-02-28 15:23 UTC
Labels: bug

**Comment by ADALIYS** [comment] 2024-06-18 07:45
如果是出现500，什么could save file错误提示的，只需要把接收方的下载地址重新设置一下就好了

**Comment by wonderhj** [comment] 2024-07-24 09:39
> 我遇到了同样的问题，我的手机是小米13，当电脑往手机传文件的时候出现 [500] Could not save file，当手机往电脑传的时候，点击媒体选了要传送的文件之后就退出来了，无法传送媒体。

i met this problem again，when i upload to 1.15.1，this problem still exist.
