### ISSUE TITLE
Feature request : Add Trusted device s

### ISSUE THREAD

**Issue by codad5** [localsend/localsend#1606] opened 2024-08-05 16:22 UTC
### Is your feature request related to a problem? Please describe.

Yes, Having to accept for my device all the time is annoying and leaving quick save all the time may lead to spamming especially when at work with colleague who would just love to piss you off

### Describe the solution you'd like

An option on the first time accepting request asks if you want to remember device, some checks like name alongside device name and IP address can be used to make the check as only name might not be enough , IP may change

**Comment by Tienisto** [comment] 2024-08-05 21:16
Duplicate of #861

**Closed** 2024-09-30 11:03 UTC
Labels: duplicate, enhancement
