### ISSUE TITLE
子网掩码不为255.255.255.0时就找不到设备

### ISSUE THREAD

**Issue by cxh2959540834** [localsend/localsend#322] opened 2023-03-25 02:33 UTC
### Is your feature request related to a problem? Please describe.

我家的wifi子网掩码为255.255.128.0，,localsend找不到对应的设备
![image](https://user-images.githubusercontent.com/76768560/227682228-b4095627-3455-4c34-b2aa-2478378a7474.png)

### Describe the solution you'd like

添加自由选择子网掩码功能

**Comment by Tienisto** [comment] 2023-03-25 14:38
Duplicate of #175

**Closed by Tienisto** 2023-03-25 14:38 UTC
