### ISSUE TITLE
Transfer speed too slow

### ISSUE THREAD

**Issue by Sinuhe96** [localsend/localsend#979] opened 2023-12-03 14:40 UTC
### Describe the bug

Not exactly a bug, but an issue nonetheless: the transfer speed is quite slow. On my Wifi 5G 802.11 ac network (between a iPad and a PC over Gigabit Ethernet), the transfer rate was approximately 2.2 Mb/s only. Using LANDrop as a control, the transfer speed was subjectively twice or trice faster (but LANDrop on the iPad crashed with memory overflow if the file was very big). The result between 2 Windows boxes is the same. The fastest speed, however, was achieved using croc.

### To reproduce

Try to transfer a 2 GB file then check for the speed.

### Expected behavior

In a Wife 802.11 ac LAN, I think the speed should be close to the theoretical maximal speed, around 25 Mb/s.

### Desktop (please complete the following information)

Windows 7 Service Pack 1

### Smartphone (please complete the following information)

iPad 2018. 
iOS 16.7.6

**Comment by Tienisto** [comment] 2023-12-05 01:55
Duplicate of #384

**Closed by Tienisto** 2023-12-05 01:55 UTC
