### ISSUE TITLE
Local send crashes when I try to send "too many" files

### ISSUE THREAD

**Issue by yagarea** [localsend/localsend#1017] opened 2023-12-09 21:15 UTC
### Describe the bug

When I am sending a couple of files it is ok. But when I try to send folder with 13821 files (23Gb) It crashes.

### To reproduce

1. try send a lot of files

### Expected behavior

not crash

### Desktop (please complete the following information)

Arch Linux

### Smartphone (please complete the following information)

Pixel 6
Graphene OS

### Additional context

I have LocalSend 1.12.0 from F-droid store.

**Comment by Tienisto** [comment] 2023-12-10 00:09
Duplicate of #907

**Closed by Tienisto** 2023-12-10 00:09 UTC
