### ISSUE TITLE
some font is not show in latest version

### ISSUE THREAD

**Issue by newyorkthink** [localsend/localsend#821] opened 2023-10-26 04:14 UTC
### Describe the bug

![image](https://github.com/localsend/localsend/assets/87791643/e8bd7e85-452b-4a27-ac9b-32ce5ddac8b8)

### To reproduce

![image](https://github.com/localsend/localsend/assets/87791643/9335dbae-6b6d-43f6-97c3-9597d4782e14)

### Expected behavior

![image](https://github.com/localsend/localsend/assets/87791643/15fa8126-ba84-4e95-ad5b-761a8684da2c)

**Comment by Tienisto** [comment] 2023-10-26 09:21
Was it correct in the previous version?

**Comment by newyorkthink** [comment] 2023-10-26 10:14
> Was it correct in the previous version?

[v1.12.0](https://github.com/localsend/localsend/releases/tag/v1.12.0)

**Comment by Tienisto** [comment] 2023-10-26 10:21
Yes, but did it work in version 1.11.1?

**Comment by newyorkthink** [comment] 2023-10-26 13:30
> Yes, but did it work in version 1.11.1?

no , 1.11.1 is not show font too, not fix, is long time

**Comment by Tienisto** [comment] 2023-10-26 13:33
Sorry, I don't use Linux. Please comment on the existing issue instead of creating a new one.

Duplicate of #644

**Closed by Tienisto** 2023-10-26 13:33 UTC
